---
apiVersion: v1
kind: Namespace
metadata:
  name: user-compte-de-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: compte-de-test
  namespace: user-compte-de-test
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: compte-de-test-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: compte-de-test
    namespace: user-compte-de-test
